- name: Download jar and war filse from Nexus
  vars: 
      war_files: 
        - genkey-2.1.1.war
        - genkey-2.1.1.jar
        

- name: Download war files 
  async: 3600 
  poll: 5 
  with_items: "{{ war_files }}" 
  command: curl -O -H "Authorization: Basic YWRtaW46U3VkbzEyMzQ1Njc4" https://5e9c-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/{{ item }}.war 
  register: async_download 
- name: Wait for downloads to complete 
  async_status: 
    jid: "{{ item.ansible_job_id }}" 
  register: async_result 
  until: async_result.finished 
  retries: 30 
  delay: 10 
- name: Proceed with subsequent stages 
  debug: msg="All war files have been downloaded." 




- name: Read file from custom directory within role
  shell: cat {{ role_path }}/config_files/combine.sh
  vars:
    src: config_files/combine.sh


- name: Debug role path
  debug:
    var: role_path



- name: Extract archive file
  remote_user: root
  become: true
  unarchive:
    src: config_files
    dest: /tmp/installation_files
    copy: yes
    extra_opts: [--strip-components=1]

- name: merge Genkey Internal files
  remote_user: root
  become: true
  shell: |
    chmod +x /tmp/installation_files/combine_config.sh
    ./tmp/installation_files/combine_config.sh SI
  any_errors_fatal: true


