- name: Download jar and war files from Nexus
  vars:
    war_files:
      - genkey-2.1.1.war
      - genkey-2.1.1.jar
    auth_header: "Basic YWRtaW46U3VkbzEyMzQ1Njc4"
  uri:
    url: "https://5e9c-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/{{ item }}"
    method: GET
    headers:
      Authorization: "Basic YWRtaW46U3VkbzEyMzQ1Njc4"
    dest: "{{ item }}"
    return_content: yes
    validate_certs: no
  with_items: "{{ war_files }}"
  register: async_download



- name: Read file from custom directory within role
  shell: cat {{ role_path }}/config_files/combine.sh
  vars:
    src: config_files/combine.sh


- name: Debug role path
  debug:
    var: role_path



- name: Extract archive file
  remote_user: root
  become: true
  unarchive:
    src: config_files
    dest: /tmp/installation_files
    copy: yes
    extra_opts: [--strip-components=1]

- name: merge Genkey Internal files
  remote_user: root
  become: true
  shell: |
    chmod +x /tmp/installation_files/combine_config.sh
    ./tmp/installation_files/combine_config.sh SI
  any_errors_fatal: true


