- name: Download artifacts from Nexus
  remote_user: root
  become: true
  vars:
    download_urls:
      - url: "https://755b-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/spire-web/2.1.1/spire-web-2.1.1.war"
        dest: "/tmp/installation_files/artifacts/web.war"
      - url: "https://755b-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/2.1.1/genkey-2.1.1.war"
        dest: "/tmp/installation_files/artifacts/rest.war"
      - url: "https://755b-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/2.1.1/genkey-2.1.1.jar"
        dest: "/tmp/installation_files/artifacts/jar-tool.jar"
  async: 3600
  poll: 5
  register: download_results

