
- name: Download artifacts from Nexus
  remote_user: root
  become: true
  vars:
    download_urls:
      - url: "https://755b-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/spire-web/2.1.1/spire-web-2.1.1.war"
        dest: "/tmp/installation_files/artifacts/web.war"
      - url: "ttps://755b-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/2.1.1/genkey-2.1.1.war"
        dest: "/tmp/installation_files/artifacts/rest.war"
      - url: "https://755b-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/2.1.1/genkey-2.1.1.jar"
        dest: "/tmp/installation_files/artifacts/jar-tool.jar"
  async: 3600
  poll: 5
  register: download_results


- name: Download spire-web file from Nexus
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    validate_certs: no
    headers:
      "Authorization": "Basic YWRtaW46U3VkbzEyMzQ1Njc4"
      "X-Requested-By": "Jenkins"
  loop: "{{ download_urls }}"
  async: 3600
  poll: 5
  when: inventory_hostname in groups['test']
  register: download_results




# - name: Wait for all downloads to complete
#   async_status:
#     jid: "{{ item.ansible_job_id }}"
#   register: download_status
#   until: download_status.finished
#   loop:
#     - "{{ download_result_1 }}"
#     - "{{ download_result_2 }}"
#     - "{{ download_result_3 }}"

    



- name: Read file from custom directory within role
  shell: cat {{ role_path }}/config_files/combine.sh
  vars:
    src: config_files/combine.sh


- name: Debug role path
  debug:
    var: role_path



- name: Extract archive file
  remote_user: root
  become: true
  unarchive:
    src: config_files
    dest: /tmp/installation_files
    copy: yes
    extra_opts: [--strip-components=1]

- name: merge Genkey Internal files
  remote_user: root
  become: true
  shell: |
    chmod +x /tmp/installation_files/combine_config.sh
    ./tmp/installation_files/combine_config.sh SI
  any_errors_fatal: true


