
- name: Download jar file from Nexus
  remote_user: root
  become: true
  get_url:
    url: " https://ab8a-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/2.1.1/genkey-2.1.1.jar"
    dest: "/tmp/installation_files/artifacts/jar-tool.jar"
    validate_certs: no
    headers:
      "Authorization": "Basic YWRtaW46U3VkbzEyMzQ1Njc4"
      "X-Requested-By": "Jenkins"
  register: download_result
  async: 600
  poll: 0

- name: Download spire-rest from Nexus
  remote_user: root
  become: true
  get_url:
    url: " https://ab8a-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/2.1.1/genkey-2.1.1.war"
    dest: "/tmp/installation_files/artifacts/web.war"
    validate_certs: no
    headers:
      "Authorization": "Basic YWRtaW46U3VkbzEyMzQ1Njc4"
      "X-Requested-By": "Jenkins"
  register: download_result
  async: 600
  poll: 0

- name: Download spire-web file from Nexus
  async: 600
  poll: 0
  remote_user: root
  become: true
  get_url:
    url: " https://ab8a-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/genkey/2.1.1/genkey-2.1.1.war"
    dest: "/tmp/installation_files/artifacts/rest.war"
    validate_certs: no
    headers:
      "Authorization": "Basic YWRtaW46U3VkbzEyMzQ1Njc4"
      "X-Requested-By": "Jenkins"
  register: download_result_3
  


# - name: Wait for all downloads to complete
#   async_status:
#     jid: "{{ download_result.ansible_job_id  }}"
#   register: download_status
#   until: download_status.finished
#   retries: 60
#   delay: 10
#   with_items:
#     - "{{ ansible_play_batch }}"

# - name: Print download results
#     debug:
#       var: download_result


- name: Extract archive file
  remote_user: root
  become: true
  unarchive:
    src: config_files
    dest: /tmp/installation_files
    copy: yes
    extra_opts: [--strip-components=1]

- name: merge Genkey Internal files
  remote_user: root
  become: true
  shell: |
    chmod +x /tmp/installation_files/combine_config.sh
    ./tmp/installation_files/combine_config.sh SI
  any_errors_fatal: true


