#!/bin/sh



export GENKEY_INTERNAL=/${DATA_DIR}/GENKEY_INTERNAL
export GENKEY_SPIRE_UPDATE_LZ=$GENKEY_INTERNAL/update
#MODIFY THE VALUES BELOW PER INSTALLATION
export CENTRAL_IP_ADDRESS=192.168.0.18
export IP_ADDRESS=192.168.0.21
