- name: Download artifacts from Nexus
  vars:
    download_urls:
    - url: "https://dab8-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/spire-si-web/3.3.1-20230215.044745-239/spire-si-web-3.3.1-20230215.044745-239.war"
      dest: "/tmp/installer_files/"
    - url: "https://dab8-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/spire-web/2.1.1/spire-web-2.1.1.war"
      dest: "/tmp/installer_files/"
    - url: "https://dab8-80-246-199-17.eu.ngrok.io/repository/maven-releases/com/genkey/si-environment/2.1.1-20230203.140829-50/si-environment-2.1.1-20230203.140829-50.jar"
      dest: "/tmp/installer_files/artifacts/"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    validate_certs: no
    headers:
      "Authorization": "Basic YWRtaW46U3VkbzEyMzQ1Njc4"
      "X-Requested-By": "Jenkins"
  loop: "{{ download_urls }}"
  async: 3600
  poll: 5
  when: inventory_hostname in groups['test']
  register: download_results


- name: Copy Gk base and extension to remote path
  become: true
  copy:
    src: .
    dest: /tmp/installation_files
  any_errors_fatal: true

   
- name: Merge GK base and extension and cleanup
  remote_user: root
  become: true
  shell: |
    cd /tmp/installation_files/config_files
    chmod +x combine.sh
    ./combine.sh SI
  any_errors_fatal: true



# - name: Wait for all downloads to complete
#   async_status:
#     jid: "{{ item.ansible_job_id }}"
#   register: download_results
#   until: download_results.finished
#   loop: "{{ download_results.results }}"


