---
      - name: Checking if Apache Exist
        stat:
           path: /usr/share/{{tomcat_version }}
        register: apache_server

      - unarchive:
          src: ./files/tomcat/{{tomcat_version }}.tar.gz
          dest: /usr/share/
        when: not apache_server.stat.exists

      - name: Create Tomcat Adjudication Folder
        file:
          path: /usr/share/tomcat_adjudication
          state: directory

      - name: Copy Tomcat Configurations to  Tomcat Adjudication Folder
        shell: "cp -r {{installer_data_dir}}/{{tomcat_version }}/*  /usr/share/tomcat_adjudication/"
     

      - name: Configure Tomcat Adjudication logs 
        file:
          src: /usr/share/tomcat_adjudication/logs
          dest: /var/log/tomcat_adjudication
          state: link

      - name: Configuring Service Scripts
        copy:
          src: ./files/service_files/adjudication.service
          dest: /etc/systemd/system/
          mode: '0755'

      - copy:
          src: ./files/service_files/adjudication
          dest: /etc/systemd/system/
          mode: '0755'

      - systemd:
          name: adjudication.service
          enabled: yes

      - copy:
          src: ./files/tomcat/tomcat_confs/{{ item }}
          dest: /usr/share/tomcat_adjudication/conf/
        with_items:
          - catalina.properties
          - context.xml
          - logging.properties

      - name: Sending catalina.sh 
        copy:
          src: ./files/tomcat/tomcat_confs/{{ item }}
          dest: /usr/share/tomcat_adjudication/bin/
        with_items:
            - catalina.sh
            - setenv.sh

      - copy:
          src: ./files/tomcat/tomcat_confs/server_adjudication.xml
          dest: /usr/share/tomcat_adjudication/conf/server.xml.template
#cTomcatSSL
      - name: Generating server.keystore
        include: cssl.yml
      
      - name: Transfering Server.keystore to Tomcat folder
        copy:
          src: /root/ssl/server.keystore
          dest: /usr/share/tomcat_adjudication
          remote_src: yes

      - file:
          dest: /usr/share/tomcat_adjudication
          owner: spire
          group: spire
          mode: '0755'
          recurse: yes

      - file:
          dest: /var/log/tomcat_adjudication/
          owner: spire
          group: spire
          recurse: yes

      - name: Removing Tomcat Default Folders
        file: 
          path: "{{ item }}"
          state: absent
        with_items:
          - /usr/share/tomcat_adjudication/webapps/ROOT
          - /usr/share/tomcat_adjudication/webapps/examples
          - /usr/share/tomcat_adjudication/webapps/docs

      #- file: 
       #   dest: /root/ssl/firewall_spire_web.sh
        #  mode: '0755'
      #- shell: " /root/ssl/firewall_spire_web.sh*"

      #- name: Installing Adjudication_ui
        #copy: 
          #src: ./files/war_files/{{ adj_war_file }}
          #dest: /usr/share/tomcat_adjudication/webapps/{{ adj_war_file }}
       
      #- name: Rename War File
        #command: mv /usr/share/tomcat_adjudication/webapps/{{ adj_war_file }} /usr/share/tomcat_adjudication/webapps/adjudication.war
        
      - name: Change Ownership
        file:
          path: /usr/share/tomcat_adjudication/webapps/
          owner: spire
          group: spire
          recurse: yes

     #- name: Start the service
       #systemd:
         #name:  adjudication.service
         #state: started

